apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trino
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/caiohmb/kube_stack.git'
    path: infra/src/helm_charts/trino
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    name: 'in-cluster'
    namespace: warehouse
    server: ''
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true