apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-operator
  namespace: {{ .Values.operator.namespace | default .Release.Namespace }}
  labels: {{- include "minio-operator.labels" . | nindent 4 }}
  {{- with .Values.operator.serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
